spring:
  application:
    name:
      personal-finance-tracker

  datasource:
    url: jdbc:mysql://localhost:3306/personal-finance-tracker
    username: root
    password: Sql@4321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

server:
  port:
    8081