package com.pft.entity.enums;

public enum ExpenseType {
    RENT_OR_MORTGAGE_PAYMENTS("Rent or mortgage payments"),
    PROPERTY_TAXES("Property taxes"),
    HOMEOWNERS_OR_RENTERS_INSURANCE("Homeowners or renters insurance"),
    MAINTENANCE_AND_REPAIRS_HOME("Maintenance and repairs (home)"),
    VEHICLE_PAYMENTS("Vehicle payments"),
    GASOLINE_OR_FUEL("Gasoline or fuel"),
    VEHICLE_INSURANCE("Vehicle insurance"),
    MAINTENANCE_AND_REPAIRS_VEHICLE("Maintenance and repairs (vehicle)"),
    PUBLIC_TRANSPORTATION_FARES("Public transportation fares"),
    PARKING_FEES("Parking fees"),
    TOLLS("Tolls"),
    GROCERIES("Groceries"),
    DINING_OUT("Dining out"),
    COFFEE_OR_SNACKS("Coffee or snacks"),
    FAST_FOOD("Fast food"),
    ELECTRICITY("Electricity"),
    WATER("Water"),
    GAS("Gas"),
    INTERNET("Internet"),
    CABLE_OR_SATELLITE_TV("Cable or satellite TV"),
    PHONE_LANDLINE("Phone (landline)"),
    PHONE_MOBILE("Phone (mobile)"),
    TRASH_COLLECTION("Trash collection"),
    HEALTH_INSURANCE("Health insurance"),
    LIFE_INSURANCE("Life insurance"),
    DISABILITY_INSURANCE("Disability insurance"),
    LONG_TERM_CARE_INSURANCE("Long-term care insurance"),
    OTHER_INSURANCE("Other types of insurance"),
    DOCTOR_VISITS("Doctor visits"),
    PRESCRIPTION_MEDICATIONS("Prescription medications"),
    DENTAL_CARE("Dental care"),
    VISION_CARE("Vision care"),
    HEALTH_INSURANCE_DEDUCTIBLES_AND_COPAYMENTS("Health insurance deductibles and copayments"),
    CREDIT_CARD_PAYMENTS("Credit card payments"),
    STUDENT_LOAN_PAYMENTS("Student loan payments"),
    PERSONAL_LOAN_PAYMENTS("Personal loan payments"),
    OTHER_LOAN_PAYMENTS("Other loan payments"),
    HAIRCUTS_AND_SALON_SERVICES("Haircuts and salon services"),
    COSMETICS_AND_TOILETRIES("Cosmetics and toiletries"),
    GYM_MEMBERSHIPS("Gym memberships"),
    SPA_TREATMENTS("Spa treatments"),
    CLOTHING_AND_ACCESSORIES("Clothing and accessories"),
    MOVIES("Movies"),
    CONCERTS("Concerts"),
    SPORTING_EVENTS("Sporting events"),
    STREAMING_SERVICES("Streaming services"),
    HOBBIES_AND_RECREATIONAL_ACTIVITIES("Hobbies and recreational activities"),
    TUITION_AND_FEES("Tuition and fees"),
    BOOKS_AND_SUPPLIES("Books and supplies"),
    EDUCATIONAL_SOFTWARE_OR_APPS("Educational software or apps"),
    WORKSHOPS_OR_SEMINARS("Workshops or seminars"),
    STUDENT_LOAN_INTEREST("Student loan interest"),
    CASH_DONATIONS("Cash donations"),
    DONATIONS_OF_GOODS("Donations of goods"),
    CONTRIBUTIONS_TO_RELIGIOUS_ORGANIZATIONS("Contributions to religious organizations"),
    CONTRIBUTIONS_TO_NONPROFITS("Contributions to nonprofits"),
    INCOME_TAXES("Income taxes"),
    SALES_TAXES("Sales taxes"),
    ESTIMATED_TAX_PAYMENTS("Estimated tax payments"),
    TAX_PREPARATION_FEES("Tax preparation fees"),
    AIRFARE("Airfare"),
    HOTELS("Hotels"),
    RENTAL_CARS("Rental cars"),
    MEALS_WHILE_TRAVELING("Meals while traveling"),
    SIGHTSEEING_AND_TOURS("Sightseeing and tours"),
    RETIREMENT_SAVINGS("Retirement savings"),
    EMERGENCY_FUND_CONTRIBUTIONS("Emergency fund contributions"),
    INVESTMENT_CONTRIBUTIONS("Investment contributions"),
    BROKERAGE_FEES("Brokerage fees"),
    FINANCIAL_ADVISOR_FEES("Financial advisor fees"),
    BANK_FEES("Bank fees"),
    LEGAL_FEES("Legal fees"),
    CHILDCARE_EXPENSES("Childcare expenses"),
    PET_CARE_EXPENSES("Pet care expenses"),
    HOME_OFFICE_EXPENSES("Home office expenses");

    private final String value;

    ExpenseType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
